# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc0ca003addc3f49348fbd1e4af5523421dc4430b7b09b1478e8d3e654ab60a62a01e256df08a5bee1f5443c62f986368863809ff60d57be7c2adcfc9c32b95b

test:
  secret_key_base: 57c4276a4afb3142392ca5b8a0ef853d26e8d585843042e81e48bab3bd92832d76b48299cbcfaf11e7e20bc0248ee3f02ace6c243acd0bc4ae91022113c8d615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
